lab1 done
MaksymHolovniak/OOPLabs pull request #1
Opened 2023-03-02 10:49 UTC by MaksymHolovniak

2023-03-02 12:01 UTC, RuslanSlobodian requested changes

2023-03-05 18:28 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/product/Product.java
> +    private int expiration;
+

2023-03-05 18:29 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/product/Product.java
> +    private int expiration;
Виконав

2023-03-05 18:29 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/product/Product.java
> +    private int expiration;
+

2023-03-06 14:13 UTC, RuslanSlobodian requested changes

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/Main.java
> +    private Product[] product;
+

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/Main.java
> +        Scanner newName = new Scanner(System.in);
+

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/Main.java
> +        String nameIn = newName.nextLine();
+

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/Main.java
> +        Scanner setPriceIn = new Scanner(System.in);
+

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/product/Product.java
> +    private String expirationString;
+

2023-03-06 15:16 UTC, MaksymHolovniak commented on lab1/src/ua/te/tk/maksym/lab0/product/Product.java
> +    private int mount;
+

2023-03-06 15:20 UTC, RuslanSlobodian approved these changes

2023-03-06 15:20 UTC, merged