lab2 done
MaksymHolovniak/OOPLabs pull request #2
Opened 2023-03-17 22:33 UTC by MaksymHolovniak

2023-03-20 14:08 UTC, RuslanSlobodian requested changes

2023-03-20 14:08 UTC, RuslanSlobodian commented on lab2/src/ua/te/tk/maksym/lab2/textchanger/TextChanger.java
> +    public void deleteWordsByCondition(){
Краще повертати результат виконання даного методу у вигляді стрінга, ніж зберігати його у атрибуті initialText.
Або зберігати його у іншому атрибуті

2023-03-20 14:08 UTC, RuslanSlobodian commented on lab2/src/ua/te/tk/maksym/lab2/textchanger/TextChanger.java
> +                wordsToRemove.add(word);
Можна було б відразу у даному масиві слова зробити пустими.
Або створити ArrayList із масиву і вже в ньомі відразу видаляти слова потрібної довжини

2023-03-22 20:10 UTC, MaksymHolovniak commented on lab2/src/ua/te/tk/maksym/lab2/textchanger/TextChanger.java
> +    public void deleteWordsByCondition(){
+

2023-03-22 20:10 UTC, MaksymHolovniak commented on lab2/src/ua/te/tk/maksym/lab2/textchanger/TextChanger.java
> +                wordsToRemove.add(word);
+

2023-04-13 11:12 UTC, RuslanSlobodian approved these changes

2023-04-13 11:13 UTC, merged